// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheLoanProviders.Data;

#nullable disable

namespace TheLoanProviders.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    partial class LoanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TheLoanProviders.Models.signuppageData", b =>
                {
                    b.Property<string>("newusername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("newuserfname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newuserpass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("newusername");

                    b.ToTable("login");
                });
#pragma warning restore 612, 618
        }
    }
}
